// <auto-generated />
using System;
using LibraryApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20260615171516_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryApi.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            CategoryId = 1,
                            IsBorrowed = false,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt",
                            CategoryId = 1,
                            IsBorrowed = false,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Erich Gamma",
                            CategoryId = 1,
                            IsBorrowed = false,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 2,
                            IsBorrowed = false,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.K. Rowling",
                            CategoryId = 2,
                            IsBorrowed = false,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 6,
                            Author = "George Orwell",
                            CategoryId = 3,
                            IsBorrowed = false,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Harper Lee",
                            CategoryId = 3,
                            IsBorrowed = false,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Dan Brown",
                            CategoryId = 4,
                            IsBorrowed = false,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Gillian Flynn",
                            CategoryId = 4,
                            IsBorrowed = false,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Robert Kiyosaki",
                            CategoryId = 5,
                            IsBorrowed = false,
                            Title = "Rich Dad Poor Dad"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Jane Austen",
                            CategoryId = 6,
                            IsBorrowed = false,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Yuval Noah Harari",
                            CategoryId = 7,
                            IsBorrowed = false,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Walter Isaacson",
                            CategoryId = 8,
                            IsBorrowed = false,
                            Title = "The Innovators"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Daniel Kahneman",
                            CategoryId = 9,
                            IsBorrowed = false,
                            Title = "Thinking, Fast and Slow"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Alan Moore",
                            CategoryId = 10,
                            IsBorrowed = false,
                            Title = "Watchmen"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "History"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Comics"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.LoanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibraryApi.Models.MemberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LibraryApi.Models.BookModel", b =>
                {
                    b.HasOne("LibraryApi.Models.CategoryModel", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryApi.Models.LoanModel", b =>
                {
                    b.HasOne("LibraryApi.Models.BookModel", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.MemberModel", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryApi.Models.BookModel", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LibraryApi.Models.CategoryModel", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryApi.Models.MemberModel", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
